apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prisma-data-proxy.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "prisma-data-proxy.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "prisma-data-proxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "prisma-data-proxy.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: init-db-migrate-deploy
          image: "{{ .Values.migrate_image.repository }}:{{ .Values.migrate_image.tag | default .Chart.AppVersion }}"
          env:
            {{- range .Values.app }}
            - name: {{ .name }}
              value: "{{ .value }}"
            {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: query-engine
              containerPort: 4467
              protocol: TCP
            - name: query-wrapper
              containerPort: 4466
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /metrics
              port: 4467
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /metrics
              port: 4467
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            {{- range .Values.app }}
            - name: {{ .name }}
              value: "{{ .value }}"
            {{- end }}
          volumeMounts:
          - name: localtime
            mountPath: /etc/localtime
      volumes:
      - name: localtime
        hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai