version: '3.8'

services:
  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=pass
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  db-deploy:
    build:
      context: .
      dockerfile: Dockerfile-db-deploy
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:pass@db:5432/postgres?schema=public
      DIRECT_URL: postgresql://postgres:pass@db:5432/postgres?schema=public
    volumes:
      - ./:/app:cached
      - node_modules:/app/node_modules
      
  graphql:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
      https-portal4466:
        condition: service_started  
    command: ./wait-for-it.sh db:5432 --timeout=120 --strict -- /app/main
    ports:
      - "4466:4466"
      - "4467:4467"
    environment:
      PRISMA_SCHEMA_FILE: ./prisma/schema.prisma
      DATABASE_URL: postgresql://postgres:pass@db:5432/postgres?schema=public
      DIRECT_URL: postgresql://postgres:pass@db:5432/postgres?schema=public
      API_KEY: custometoken
      LISTEN_ADDR: "0.0.0.0:4466"
      ENABLE_MIGRATION: "false"
      ENABLE_SLEEP_MODE: "false"
      QUERY_ENGINE_LOG: "true"
      QUERY_ENGINE_HOST_BIND: "0.0.0.0"
      ENABLE_OPEN_TELEMETRY: "false"
      OPEN_TELEMETRY_ENDPOINT: "otel:4317"
      ENABLE_TELEMETRY_IN_RESPONSE: "true"
      FMT_SQL: 1
      PRODUCTION: "false"

  https-portal4466:
    depends_on:
      db:
        condition: service_healthy
    image: steveltn/https-portal:1
    ports:
      - "443:443"
    environment:
      STAGE: local
      DOMAINS: 'https-portal4466 -> http://graphql:4466'
    volumes:
      - ./ssl-certs:/var/lib/https-portal

  dev:
    image: node:18.3.0-bullseye-slim
    working_dir: /app
    entrypoint: /app/entrypoint.sh
    command: tail -f /dev/null
    environment:
      DATABASE_URL: prisma://https-portal4466/?api_key=custometoken
      NODE_TLS_REJECT_UNAUTHORIZED: "0"
      DIRECT_URL: postgresql://postgres:pass@db:5432/postgres?schema=public
      MIGRATE: "true"
    volumes:
      - ./:/app:cached
      - node_modules_dev:/app/node_modules
    depends_on:
      db:
        condition: service_healthy
      db-deploy:
        condition: service_completed_successfully

volumes:
  node_modules:
  node_modules_dev: