FROM node:18-alpine3.17

ENV TZ Asia/Shanghai
RUN apk add alpine-conf tzdata tini --no-cache && \
    /sbin/setup-timezone -z Asia/Shanghai && \
    apk del alpine-conf

WORKDIR /app

COPY package.json .
COPY yarn.lock .
RUN yarn

COPY ./prisma ./prisma

CMD [ "yarn", "prisma", "migrate", "deploy" ]