# Default values for prisma-data-proxy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

domain: data-proxy.prisma.example.com

image:
  repository: ghcr.io/zsnmwy/prisma-data-proxy-windmill-template
  pullPolicy: IfNotPresent
  tag: "v0.1.0"

migrate_image:
  repository: ghcr.io/zsnmwy/prisma-migrate-db-windmill-template
  pullPolicy: IfNotPresent
  tag: "v0.1.0"

imagePullSecrets:
  - name: pull-secrets
nameOverride: ""
fullnameOverride: ""

app:
  - name: PRISMA_SCHEMA_FILE
    value: ./schema.prisma
  - name: DATABASE_URL
    value: postgresql://postgres:pass@db:5432/postgres?schema=public
  - name: DIRECT_URL
    value: postgresql://postgres:pass@db:5432/postgres?schema=public
  - name: API_KEY
    value: custometoken
  - name: LISTEN_ADDR
    value: "0.0.0.0:4466"
  - name: ENABLE_MIGRATION
    value: false
  - name: ENABLE_SLEEP_MODE
    value: false
  - name: QUERY_ENGINE_LOG
    value: true
  - name: QUERY_ENGINE_HOST_BIND
    value: 0.0.0.0
  - name: ENABLE_OPEN_TELEMETRY
    value: false
  - name: OPEN_TELEMETRY_ENDPOINT
    value: otel:4317
  - name: ENABLE_TELEMETRY_IN_RESPONSE
    value: true
  - name: FMT_SQL
    value: 1
  - name: PRODUCTION
    value: false
  
service:
  type: ClusterIP
  port: 3000

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 2000m
    memory: 2000Mi
  requests:
    cpu: 100m
    memory: 128Mi
    