name: Build Data Proxy

on:
  push:
    branches: [ "master" ]
    paths:
      - '**.prisma'
      - 'package.json'
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.5.2
      with:
        # Version Spec of the version to use.  Examples: 12.x, 10.15.1, >=10.15.0
        node-version: 18.3.0
        
    - name: Yarn Install
      run: yarn

    - name: Get Package Version
      run: |
        echo "package_version=$(jq -r .version package.json)" >> "$GITHUB_ENV"
        yarn prisma version | tee prisma_version.txt
        echo "prisma_version=$(cat prisma_version.txt| grep 'Default Engines Hash' | cut -d ':' -f2 | tr -d '[:blank:]')" >> "$GITHUB_ENV"
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and push Docker images - Prisma Data Proxy
      uses: docker/build-push-action@v4.1.1
      with:
        context: .
        platforms: linux/amd64
        file: Dockerfile
        tags: |
          ghcr.io/${{ github.actor }}/prisma-data-proxy-windmill-template:${{ env.package_version }}
        push: true
        build-args: |
          PRISMA_VERSION=${{ env.prisma_version }}

    - name: Build and push Docker images - Prisma Migrate DB
      uses: docker/build-push-action@v4.1.1
      with:
        context: .
        platforms: linux/amd64
        file: Dockerfile-db-deploy
        tags: |
          ghcr.io/${{ github.actor }}/prisma-migrate-db-windmill-template:${{ env.package_version }}
        push: true
        build-args: |
          PRISMA_VERSION=${{ env.prisma_version }}